jdk:
  - openjdk11

jobs:
  include:
    - stage: CodeQualityAndTesting
      script: ./gradlew sonarqube
    - stage: DeployingToHeroku
      deploy:
        provider: heroku
        api-key:
          secure: $HEROKU_API_KEY
        app: gamestore-api

addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN
