jdk:
  - openjdk11

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: DeployingToHeroku
      deploy:
        provider: heroku
        api-key: $HEROKU_API_KEY
        app:
          master: yagan93
          production: yagan93
        run: "rake db:migrate"
addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN

script:
  - ./gradlew sonarqube
