language: java

jdk:
  - openjdk11

node_js:
  - lts/*

stages:
  #- continousIntegration
  - continousDelivery

before_install:
  - chmod +x gradlew

install:
  - node -v
  - npm install -g newman

addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN

jobs:
  include:
    #- stage: continousIntegration
     # script: ./gradlew sonarqube
    - stage: continousDelivery
      deploy:
        provider: heroku
        api-key: $HEROKU_API_KEY
        app: $HEROKU_STAGING_APP
      after_success:
      script:
        - newman run src/test/java/systemtests/collection/CRUD.postman_collection -e src/test/java/systemtests/environement/uk223.postman_environment.json
