jdk:
  - openjdk11

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: DeployingToHeroku
      deploy:
        provider: heroku
        api-key:
          secure: $HEROKU_API_KEY
        app: yagan93

addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN

script:
  - ./gradlew sonarqube
