jdk:
  - openjdk11

before_install:
  - chmod +x gradlew

addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN

script:
  - ./gradlew sonarqube

jobs:
  include:
    - stage: DeployingToHeroku
      deploy:
        provider: heroku
        api-key: $HEROKU_API_KEY
        app: yagan93
